[package]
name = "hazy_derive"
version = "0.1.0"
authors = ["Esteban Küber <esteban@kuber.com.ar>"]
edition = "2018"
description = "Opaque Debug replacement with per-field configuration"
license = "MIT"

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"

[lib]
proc-macro = true